version: '2'

services:
  webapp:
    build:
      args:
        source: obj/empty-folder-for-docker-build
    labels:
      - "com.microsoft.development.program=dotnet"
      - "com.microsoft.development.arguments=--additionalprobingpath /root/.nuget/packages bin/{Configuration}/{Framework}/WebApp.dll"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
