version: '2'

services:
  webapp:
    image: weidazhao/webapp:dev
    build:
      args:
        source: obj/empty-folder-for-docker-build
    labels:
      - "com.microsoft.visualstudio.debuggee.program=dotnet"
      - "com.microsoft.visualstudio.debuggee.arguments=--additionalprobingpath /root/.nuget/packages bin/{Configuration}/{Framework}/WebApp.dll"
      - "com.microsoft.visualstudio.debuggee.workingdirectory=/app"
      - "com.microsoft.visualstudio.debuggee.terminateprogram=/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
      - "com.microsoft.visualstudio.debugger.program=/clrdbg/clrdbg"
      - "com.microsoft.visualstudio.debugger.arguments=--interpreter=mi"
      - "com.microsoft.visualstudio.debugger.targetarchitecture=x64"
      - "com.microsoft.visualstudio.debugger.mimode=clrdbg"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
